#!/bin/sh

print_usage()
{
	echo "Usage: git-tarchanges ARCHIVE"
	echo "-h, --help	print this help"
}

if [[ $# == 0 ]]; then
	print_usage
	exit 1
elif [[ $1 == "-h" || $1 == "--help" ]]; then
	print_usage
	exit 0
fi

if [ ! -d .git ]; then
	echo "Must be in top level directory."
	exit 1
fi

tar -czvf $1 `git diff --name-only`
