#!/bin/sh

DESTDIR=~/Code/git/patches

if [ $# -lt 2 ]; then
	echo "git-dir-format-patch <dir> <count> [destdir]"
	exit 1
fi

if [ $# -eq 3 ]; then
	DESTDIR=$3
fi

if [ ! -d $DESTDIR ]; then
	echo "Destination directory does not exist!"
	exit 1
fi

SERIESFILE=$DESTDIR/series.lst

rm -f $SERIESFILE

for sha in `git log $GIT_EXARGS --pretty=%H $1 | head -n $2`; do
	git format-patch -1 -o $DESTDIR $sha | tee -a $SERIESFILE
done
